news_url: "https://news.railstutorial.org/"
contact_url: "https://www.railstutorial.org/contact"
help_url: "https://www.railstutorial.org/help"
book_url: "https://www.railstutorial.org/book"
tutorial_url: "https://www.railstutorial.org/"
tutorial_text: "Ruby on Rails Tutorial"
tutorial_help_text: "Rails Tutorial help page"
tutorial_contact_text: "contact page"
app_logo_text: "Sample App"
remember_me_status: "1"
maximum_name_length: 50
maximum_email_length: 255
minimum_password_length: 6
image_size: 80
